### ISSUE TITLE
A (probably easier) alternative installation for CUDA 11

### ISSUE THREAD

**Issue by liuQuan98** [Runjian-Chen/CO3#2]
Hi Chen! Thanks a lot for your excellent work and its open-sourced code!

I am recently trying out different environment builds on a CUDA 11 machine. I found out an installation that worked for me, looks similar to your claimed environment (python 3.8 + torch 1.8), bug-free during installation, and require no source-code compiling.

A major issue with the previous version is that mmdet3d, mmdet, mmcv and mmsegmentation just released a whole bunch of incompatible version so that `pip install XXX.git` will not work as intended (latest incompatible version is installed).

My installation reads as follows:

```
conda create -n open-mmlab python=3.8 -y
conda activate open-mmlab
conda install pytorch=1.8 torchvision=0.9.0 cudatoolkit=11.1 -c pytorch -c nvidia
pip install mmcv-full==1.4.5 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html --no-cache-dir
pip install mmdet==2.22.0 mmsegmentation==0.20.0
wget https://github.com/open-mmlab/mmdetection3d/archive/refs/tags/v0.18.0.tar.gz
tar -xvf v0.18.0.tar.gz
cd mmdetection3d
pip install -v -e .
pip install git+https://github.com/klintan/pypcd.git
pip install timm
```

**Comment by Runjian-Chen** [comment]
Thanks for your interest in our work! 

Yes, as we state in the ReadMe.md, we use mmcv-full==1.4.5 and mmdet==2.22.0 for the project. It seems that you can use "pip install mmcv-full==1.4.5 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html --no-cache-dir" to directly download the whl and install mmcv-full. If you provide a wrong link (for example "torch160" in the original link), pip will download mmcv-full and build it from source, which costs a lot of time.

**Comment by liuQuan98** [comment]
> Thanks for your interest in our work!
> 
> Yes, as we state in the ReadMe.md, we use mmcv-full==1.4.5 and mmdet==2.22.0 for the project. It seems that you can use "pip install mmcv-full==1.4.5 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html --no-cache-dir" to directly download the whl and install mmcv-full. If you provide a wrong link (for example "torch160" in the original link), pip will download mmcv-full and build it from source, which costs a lot of time.

Oh, thanks! This was my typo. I will edit the original issue in case anyone get misled.
