### ISSUE TITLE
Errno 2] No such file or directory virtuallidar_to_world/006315.json

### ISSUE THREAD

**Issue by oceanechy** [Runjian-Chen/CO3#4]
Thank you very much for your excellent work. When I downloaded the data set, I found that there was a lack of data. The official data seemed to be only the data of training and validation data set.
FileNotFoundError: [Errno 2] No such file or directory:  'data/DAIR-V2X/cooperative-dataset/infrastructure-side/calib/virtuallidar_to_world/006315.json'

I would like to ask you how to obtain the test data of DAIR-V2X-C, or the complete data, thank you again！

**Comment by Runjian-Chen** [comment]
Thanks for your interest in our work! Actually, we did not use the test set for pre-training CO3. I think you could turn to the authors in DAIR-V2X for help in the test set problem. Please feel free to reach out if there exists any other problems related to CO3.

**Comment by oceanechy** [comment]
> Thanks for your interest in our work! Actually, we did not use the test set for pre-training CO3. I think you could turn to the authors in DAIR-V2X for help in the test set problem. Please feel free to reach out if there exists any other problems related to CO3.

Thank you very much for your reply. I am currently encountering an issue with the dataset. Information such as infrastructure side/velodyne/006315.pcd is used in the data_info.json file in the cooperative folder. However, the downloaded DAIR-V2X-C dataset does not have a file 006315.pcd in the velodyne folder, resulting in an error. Could you please advise me on how your dataset was downloaded and whether the following dataset was used（https://thudair.baai.ac.cn/coop-dtest）? Thank you again!

**Comment by Runjian-Chen** [comment]
Hello~ Sorry for the late reply.

It seems that the problem is related to the dataset itself. Actually I downloaded the dataset from the link you provided. But I downloaded it two years ago. I am not sure whether they changed it. For initial attempts, maybe you can simply skip that sample if only one is missed.

**Comment by oceanechy** [comment]
> Hello~ Sorry for the late reply.
> 
> It seems that the problem is related to the dataset itself. Actually I downloaded the dataset from the link you provided. But I downloaded it two years ago. I am not sure whether they changed it. For initial attempts, maybe you can simply skip that sample if only one is missed.

Okay, I know how to solve it. Thank you
